### ISSUE TITLE
No GPU use in windows 7

### ISSUE THREAD

**Issue by SandipBR** [AlturosDestinations/Alturos.Yolo#23]
Hi
I have windows 7 with CUDA toolkit 9.2 and placed the cudnn64_7.dll in the x64 directory. i have GForce 1050ti graphics card. c++ redist for 2017 is also installed. When running the project it uses only CPU and NOT GPU. I use Visual Studio 2015 Community Edition for the project and the package installed from Nuget. Can anyone help me please.  I really need to get it work.
Thanks

**Comment by SandipBR** [comment]
I fixed the issue by myself. The EnvironmentReport is a good method to detect the issues. 
Thanks again for making such a great work. I appreciate it.
