### ISSUE TITLE
System.DllNotFoundException - Unable to load DLL 'x64\yolo_cpp_dll_gpu.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by dttson** [AlturosDestinations/Alturos.Yolo#6]
Hi, i got this error when trying to test on a gpu environment. Could you help me?

**Comment by tinohager** [comment]
Exists the x64 folder on the destination?

**Comment by chesslove** [comment]
Thank for your reply, i recorded a video to show step by step. Hope it could help.
https://youtu.be/wChPfgpk-0k

**Comment by tinohager** [comment]
Dont change the existing code in the YoloWrapper.cs, copy the cudnn64_7.dll in the x64 output directory.

**Comment by chesslove** [comment]
**It is working perfectly now, thank for your help!**

**Comment by omarattia3143** [comment]
i have the same problem i couldn't fix it ... is there a problem with nvidia optimus ?

**Comment by tinohager** [comment]
@omarattia3143 have you some result with this tool "%PROGRAMFILES%\NVIDIA Corporation\NVSMI\nvidia-smi.exe"?

https://stackoverflow.com/questions/30693704/no-cuda-capable-device-is-detected-with-cuda-capable-gpu-installed-win7

**Comment by omarattia3143** [comment]
thanks for the fast replay, here is the result >

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 411.31                 Driver Version: 411.31                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 920M       WDDM  | 00000000:08:00.0 N/A |                  N/A |
| N/A   44C    P8    N/A /  N/A |     38MiB /  2048MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

**Comment by tinohager** [comment]
Do you have experience with c++? I call this method in background [cudaGetDeviceCount](https://www.cs.cmu.edu/afs/cs/academic/class/15668-s11/www/cuda-doc/html/group__CUDART__DEVICE_g665468e8cb33be42434f11bee2684ec9.html).

https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.cpp -> int get_device_count() {

**Comment by omarattia3143** [comment]
i understand the code ... but i can't figure out the problem with gpu though everything works great with cpu. as soon as i put cudnn64_7.dll i get this exact error building for x64:
 System.DllNotFoundException: 'Unable to load DLL 'x64\yolo_cpp_dll_gpu.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

i think i have to try it on a different machine.

**Comment by tinohager** [comment]
Check you have missing dependency and send a screenshot please
http://www.dependencywalker.com/

**Comment by tinohager** [comment]
Have you copy the cudnn64_7.dll in the x64 directory.?

**Comment by omarattia3143** [comment]
yes

**Comment by omarattia3143** [comment]
> Have you copy the cudnn64_7.dll in the x64 directory.?

yes i did
also here is dependency walker

![image](https://user-images.githubusercontent.com/33941687/48163962-d1357900-e2e9-11e8-9af4-354a44e639eb.png)

**Comment by tinohager** [comment]
Your system miss the `msvcr100.dll`

**Comment by tinohager** [comment]
[msvcr100.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/2559431/msvcr100.zip)

**Comment by tinohager** [comment]
Try this dll please [msvcr100.zip](https://github.com/AlturosDestinations/Alturos.Yolo/files/2559449/msvcr100.zip)

**Comment by omarattia3143** [comment]
excuse my limited knowledge, my msvcr100 files are OK tried different version and tried yours and even  Microsoft Visual C++ Redistributable for Visual Studio 2017 ... is there problem with my kernel32.dll too? 
thank you for helping me i will take it from here and try to fix it.

**Comment by omarattia3143** [comment]
finally the detection has been using gpu with these configurations:
Nvidia Driver 416.34
CUDA 9.2.148
cuNdd 7.1.4
and fixing all the missing dependencies using dependency walker 
thanks @tinohager

**Comment by tinohager** [comment]
perfect 👍
