### ISSUE TITLE
Cuda Error

### ISSUE THREAD

**Issue by pokernet** [AlturosDestinations/Alturos.Yolo#91]
hi

from the last version cuda stop working for me
i try to update nvidia drivers and cuda to 10.2 , not working

i down to 10.1 cuda and old driver - not working

if i update the driver its auto update the cuda to 10.2

what i am doing worng
i include screen capture :

![Capture_dll2](https://user-images.githubusercontent.com/19148791/71356243-46b1e680-258a-11ea-96d5-46d7c9c0e458.JPG)
![Capture_dll3](https://user-images.githubusercontent.com/19148791/71356244-474a7d00-258a-11ea-8e79-1c5e381d22cf.JPG)
![Capture_dll](https://user-images.githubusercontent.com/19148791/71356245-474a7d00-258a-11ea-9e63-76770d8c07eb.JPG)

**Comment by tinohager** [comment]
Last version is 2.6.2 or 3.0.0-alpha?

**Comment by pokernet** [comment]
2.6.2

**Comment by tinohager** [comment]
Which error do you receive?

**Comment by pokernet** [comment]
It's just don't use the the gpu
Only cpu

**Comment by tinohager** [comment]
What is the result of `GetEnvironmentReport` https://github.com/AlturosDestinations/Alturos.Yolo/blob/8582554173b3b2a6c523bb2f2ad46d74c29f4ff7/src/Alturos.Yolo/YoloWrapper.cs#L111

**Comment by pokernet** [comment]
![1](https://user-images.githubusercontent.com/19148791/71375629-9cf14a80-25c7-11ea-94ff-23ae162c432c.jpg)

**Comment by tinohager** [comment]
The Cudnn is very simple...

```cs
if (File.Exists(@"x64\cudnn64_7.dll"))
{
    report.CudnnExists = true;
}
```

**Comment by tinohager** [comment]
Maybe this can help you https://github.com/AlturosDestinations/Alturos.Yolo/issues/57

**Comment by pokernet** [comment]
hi
thanks for the help

i found the problem but i dont get it

this problem is 
yolo c# is call from my lib dll xxx.dll 
xxx. dll call from main application xxx.exe
the xxx.dll is in /plugins folder inside the main xxx.exe folder
and the /x64 folder in  xxx.dll folder 
yolo lookup the cuda file in the main folder of xxx.exe
and i put the x64 folder in the /plugins folder with my xxx.dll 
after i copy the x64 folder to the main exe folder from xxx.dll folder all working ok
exe is in /main/ and xxx.dll is in /main/plugins  any option to fix this ?
